"""empty message

Revision ID: 56703a08019e
Revises: f9425ce4f6a1
Create Date: 2023-04-28 15:58:07.253813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56703a08019e'
down_revision = 'f9425ce4f6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
